modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="clearview"
version="${file.jarVersion}"
displayName="Lava Clear View"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lava-clear-view"
description="Allow you to see more easily under lava, when you have fire resistance."